version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  accounts:
    container_name: accounts
    build:
      context: .
      dockerfile: ./apps/accounts/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - database
      - rabbitmq
    ports:
      - '8000:8000'

  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - database
      - rabbitmq
    ports:
      - '8001:8001'
